config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'notes#index'
  resources :notes, only: [:index, :create, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :lists, only: [:create, :destroy]
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  def self.search(search)
    if search != ""
      Note.where('title LIKE(?)', "%#{search}%")
    else
      Note.order(id: "DESC")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  # PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  # validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :notes
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def create
    list = List.create(list_params)
    render json: { post: list }
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to root_path
  end

  def list_params
    params.require(:list).permit(:list_text).merge(user_id: current_user.id)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @note = Note.new
    @notes = Note.order(id: "DESC")
    @list = List.new
    @lists = List.order(id: "ASC")
  end

  def create
    note = Note.create(note_params)
    render json: { post: note }
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to root_path
  end

  def search
    @notes = Note.search(params[:keyword])
    @note = Note.new
    @list = List.new
    @lists = List.order(id: "ASC")
  end

  private

  def note_params
    params.require(:note).permit(:title, :content).merge(user_id: current_user.id)
  end

  def list_params
    params.require(:list).permit(:list_text).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <title>ListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_main.html.erb
<div class="main bg-white col-9">

  <div class="main-header border-start d-flex justify-content-start align-items-center">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary ms-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="bi bi-pencil-square" style="font-size:20px"></i>
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">新規メモ</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <%= form_with model: @note, id: "form" do |f| %>
            <div class="modal-body">
              <div class="form-group">
                <%= f.label :title, "タイトル" %>
                <%= f.text_field :title, class: "form-control", id: "title" %>
              </div>
              <div class="form-group">
                <%= f.label :content, "テキスト" %>
                <%= f.text_area :content, class: "form-control", id: "content" %>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
              <%= f.submit "作成する", class: "btn btn-primary", id: "submit" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= form_with url: search_notes_path, method: :get, class: "search-form ms-3", local: true do |form| %>
      <%= form.text_field :keyword, placeholder: "タイトルを検索", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn px-1" %>
    <% end %>
  </div>
  
  <div class="main-text d-flex flex-wrap overflow-scroll", id="list">

    <% @notes.each do |note| %>
      <div class="card m-3" style="width: 20rem;">
        <div class="card-body overflow-scroll" style="height: 300px">
          <h5 class="card-title shadow ms-2" style="font-size:23px">
            <%= note.title %>
          </h5>
          <div class="d-flex justify-content-between">
            <h6 class="card-date pt-2">
              <%= note.created_at %>
            </h6>
            <%= link_to note_path(note), method: :delete do %>
              <i class="bi bi-trash" style="font-size:20px"></i>
            <% end %>
          </div>
          <p class="card-text overflow-scroll">
            <%= note.content %>
          </p>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/notes/_side_bar.html.erb
<div class="sidebar bg-light col-3">

  <div class="sidebar-header shadow d-flex align-items-center">
    <%= link_to root_path do %>
      <i class="bi bi-journal-text mx-2" style="font-size:24px">ListApp</i>
    <% end %>
  </div>

  <div class="lists-form pt-4 px-2">

    <div class="list-form">
      <%= form_with model: @list, id: "list-form" do |f| %>
        <div>
          <%= f.label :list_text, "ToDoリスト", class: "list-label" %>
        </div>
        <div>
          <%= f.text_field :list_text, class: "text-field", id: "text", autofocus: true %>
          <%= f.submit "作成", class: "btn btn-primary", id: "list-submit" %>
        </div>
      <% end %>
    </div>

  </div>
  <div class="lists overflow-scroll px-2">

    <div class="lists-text", id="list-text">
      <% @lists.each do |list| %>
        <div class="list-text d-flex justify-content-between p-2 my-1">
          <label>
            <input type="checkbox">
            <%= list.list_text %>
          </label>
          <%= link_to list_path(list), method: :delete, class: "me-2" do %>
            <i class="bi bi-trash" style="font-size:20px"></i>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div class="sidebar-footer d-flex justify-content-between align-items-center">

    <%= link_to destroy_user_session_path, method: :delete do %>
      <button type="button" class="btn btn-danger ms-2">
        <i class="bi bi-door-closed" style="font-size:20px"></i>
      </button>
    <% end %>
    <%= link_to edit_user_path(current_user) do %>
      <button type="button" class="btn btn-secondary ms-2">
        <i class="bi bi-person-circle" style="font-size:20px"></i>
      </button>
    <% end %>

  </div>

</div>

app/views/notes/index.html.erb
<div class="wrapper d-flex">

  <%= render "side_bar" %>

  <%= render "main" %>

</div>

app/views/notes/search.html.erb
<div class="wrapper d-flex">

  <%= render "side_bar" %>

  <%= render "main" %>

</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
  <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
      <%= link_to "戻る", :back, class: 'btn' %>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f| %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname %>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true %>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email %>
          </div>
          <div class='field-input'>
            <%= f.email_field :email %>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>